adopskuy/urls.py
from django.contrib import admin
from django.urls import path, include
from adopskuy.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('artikel/', include('artikel.urls')),
    path('donasi/', include('donasi.urls')),
    path('adopsi/', include('adopsi.urls')),
    path('akun/', include('akun.urls')),
]

akun/urls.py
from django.urls import path

from .views import register_view, login_view, logout_view

app_name = 'akun'

urlpatterns = [
    path('daftar/', register_view, name='daftar'),
    path('masuk/', login_view, name='login'),
    path('keluar/', logout_view, name='keluar')
]

donasi/urls.py
from django.urls import path

from . import views

app_name = 'donasi'


urlpatterns = [
    path('', views.home, name='home'),
    path('bayar/', views.bayar, name='bayar'),
    path('d/<int:donasi_id>/', views.detail, name='detail'),
    path('d/<int:donasi_id>/kirim', views.kirim, name='kirim'),
    path('gambar/', views.ubah_gambar, name='ubah-gambar'),
    path('admin/', views.admin_home, name='admin-home'),
    path('admin/d/<int:donasi_id>/', views.admin_detail, name='admin-detail'),
]

donasi/models.py
from base64 import b64encode

from django.db import models
from django.utils.safestring import mark_safe

from akun.models import User


class Donasi(models.Model):

    class StatusDonasi(models.TextChoices):
        DISETUJUI = 'setuju', 'Disetujui'
        DITOLAK = 'tolak', 'Ditolak'

    judul = models.CharField(max_length=256)
    gambar = models.BinaryField(null=True, blank=True)
    deskripsi = models.TextField()
    target = models.BigIntegerField()
    dana_terkumpul = models.BigIntegerField(blank=True, default=0)
    banyak_pendonasi = models.IntegerField(blank=True, default=0)
    pemilik = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True)
    admin_penyetuju = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='menyutujui_donasi',
        null=True,
        blank=True)
    status_donasi = models.CharField(
        max_length=16,
        choices=StatusDonasi.choices,
        null=True,
        blank=True)

    def __str__(self):
        return self.judul

    def get_image_data(self):
        if self.gambar == None:
            return ""
        return mark_safe('data:image/png;base64,{}'.format(
            b64encode(self.gambar).decode('utf8')))

donasi/views.py
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Donasi


def home(request):
    context = {
        'page_title': 'Donasi',
        'all_donasi': Donasi.objects.filter(status_donasi=Donasi.StatusDonasi.DISETUJUI),
    }

    return render(request, 'donasi/list.html', context)


def detail(request, donasi_id):
    donasi = get_object_or_404(Donasi, id=donasi_id)

    context = {
        'page_title': f'Donasi {donasi.judul}',
        'donasi': donasi,
    }

    return render(request, 'donasi/detail.html', context)


def bayar(request):
    donasi_id = request.POST['donasi_id']
    donasi = get_object_or_404(Donasi, id=donasi_id)

    context = {
        'page_title': f'Kirim Donasi ke {donasi.judul}',
        'nominal': request.POST['nominal'],
        'bank': request.POST['bayar'],
        'donasi': donasi,
    }

    return render(request, 'donasi/bayar.html', context)

@login_required(login_url="akun:login")
def admin_home(request):
    if not request.user.admin:
        raise PermissionDenied

    context = {
        'page_title': 'Admin Donasi',
        'unverified_donasi': Donasi.objects.filter(status_donasi=None),
        'donasi_diterima': Donasi.objects.filter(status_donasi=Donasi.StatusDonasi.DISETUJUI),
        'donasi_ditolak': Donasi.objects.filter(status_donasi=Donasi.StatusDonasi.DITOLAK),
    }

    return render(request, 'donasi/admin_list.html', context)

@login_required(login_url="akun:login")
def admin_detail(request, donasi_id):
    if not request.user.admin:
        raise PermissionDenied

    donasi = get_object_or_404(Donasi, id=donasi_id)

    if request.method == 'POST':
        status = request.POST.get('status')
        if status == 'TERIMA':
            donasi.status_donasi = Donasi.StatusDonasi.DISETUJUI
            donasi.admin_penyetuju = request.user
            donasi.save()
        elif status == 'TOLAK':
            donasi.status_donasi = Donasi.StatusDonasi.DITOLAK
            donasi.admin_penyetuju = request.user
            donasi.save()
        return redirect('donasi:admin-home')


    context = {
        'page_title': f'Setujui {donasi.judul}',
        'donasi': donasi,
    }

    return render(request, 'donasi/admin_detail.html', context)

@login_required(login_url="akun:login")
def ubah_gambar(request):
    donasi_id = request.POST.get('donasi_id')
    donasi = get_object_or_404(Donasi, id=donasi_id)

    if request.user != donasi.pemilik:
        raise PermissionDenied

    donasi.gambar = request.FILES['gambar'].file.read()
    donasi.save()

    return redirect('donasi:detail', donasi_id)

def kirim(request, donasi_id):
    nominal = request.POST.get('nominal')

    try:
        donasi = Donasi.objects.get(id=donasi_id)
    except ObjectDoesNotExist:
        return redirect("donasi:home")

    donasi.dana_terkumpul += int(nominal)
    donasi.save()

    return redirect('donasi:detail', donasi_id)

donasi/templates/donasi/admin_detail.html
{% extends 'adopskuy/base.html' %}
{% load static %}

{% block style %}
<link href="{% static 'donasi/donasi.css' %}" rel="stylesheet">
<style>
div.image {
  margin: 40px 0 20px;
  height: 300px;
  background-color: #294e28;
  background-image: url({{ donasi.get_image_data }});
  background-size: cover;
  background-position: center;
}
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="image"></div>
  <h1>{{ donasi.judul }}</h1>
  <h2 class="my-2">
    Status:
    {% if donasi.status_donasi == None %}
    Belum Diverifikasi
    {% elif donasi.status_donasi == 'setuju' %}
    <span style="color: green">Diterima</span>
    {% elif donasi.status_donasi == 'tolak' %}
    <span style="color: red">Ditolak</span>
    {% endif %}
  </h2>
  <form action="{% url 'donasi:admin-detail' donasi.id %}" method="POST">
    {% csrf_token %}
    Ubah status:
    <input class="btn btn-success" type="submit" name="status" value="TERIMA">
    <input class="btn btn-danger" type="submit" name="status" value="TOLAK">
  </form>
  <div class="card my-3">
    <div class="card-body">
      <h2 class="card-title">Cerita</h2>
      <p>{{ donasi.deskripsi }}</p>
    </div>
  </div>
  {% with donasi.pemilik as pemilik %}
  <div class="card my-3">
    <div class="card-body">
      <h3 class="card-title">Data Pemilik</h3>
      <table>
        <tr>
          <td>Nama</td>
          <td>: {{ pemilik.nama_lengkap }}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td>: {{ pemilik.email }}</td>
        </tr>
        <tr>
          <td>Alamat</td>
          <td>: {{ pemilik.alamat }}</td>
        </tr>
        <tr>
          <td>Nomor Telepon</td>
          <td>: {{ pemilik.phone_number }}</td>
        </tr>
      </table>
    </div>
  </div>
  {% endwith %}
  <div class="grey-screen" onclick="closePopup()"></div>
  <div class="card card-centered">
    <form id="form-popup" method="POST" action="{% url 'donasi:bayar' %}">
      {% csrf_token %}
      <input type="hidden" name="donasi_id" value="{{ donasi.id }}">
      <div class="card-body choose-nominal">
        <h3>Nominal</h3>
        <label for="10000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="10000" name="nominal" value="10000">
              Rp 10.000
            </div>
          </div>
        </label>
        <label for="20000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="20000" name="nominal" value="20000">
              Rp 20.000
            </div>
          </div>
        </label>
        <label for="50000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="50000" name="nominal" value="50000">
              Rp 50.000
            </div>
          </div>
        </label>
        <label for="100000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="100000" name="nominal" value="100000">
              Rp 100.000
            </div>
          </div>
        </label>
      </div>
      <div class="card-body choose-bayar" style="display: none">
        <h3>Metode Pembayaran</h3>
        <label for="bni">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="bni" name="bayar" value="bni">
              BNI
            </div>
          </div>
        </label>
        <label for="bca">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="bca" name="bayar" value="bca">
              BCA
            </div>
          </div>
        </label>
        <label for="mandiri">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="mandiri" name="bayar" value="mandiri">
              Mandiri
            </div>
          </div>
        </label>
      </div>
    </form>
  </div>
</div>
{% endblock %}

donasi/templates/donasi/admin_list.html
{% extends 'adopskuy/base.html' %}
{% load static %}

{% block style %}
<style>
.card {
  margin: 10px 0;
  position: relative;
}
.judul {
  font-size: 18px;
  font-weight: bold;
}
.pemilik {
  font-size: 14px;
}
.card .image {
  position: absolute;
  right: 0;
  top: 0;
  height: 100%;
  width: 300px;
  background-color: #294E28;
  background-size: cover;
  background-position: center;
}
</style>
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mt-5">Konfirmasi Donasi</h1>
  <div>
    {% if unverified_donasi|length != 0 %}
    {% for donasi in unverified_donasi %}
    <a href="{% url 'donasi:admin-detail' donasi.id %}" style="color: black">
      <div class="card">
        <div class="card-body">
          <p class="judul">{{ donasi.judul }}</p>
          <p class="pemilik">{{ donasi.pemilik }}</p>
          <p class="terkumpul">Terkumpul: Rp. {{ donasi.dana_terkumpul }}</p>
          <div class="image" style="background-image: url({{ donasi.get_image_data }});"></div>
        </div>
      </div>
    </a>
    {% endfor %}
    {% else %}
    Donasi masih kosong...
    {% endif %}
  </div>
  <h2 class="mt-5">Donasi Diterima</h2>
  <div>
    {% if donasi_diterima|length != 0 %}
    {% for donasi in donasi_diterima %}
    <a href="{% url 'donasi:admin-detail' donasi.id %}" style="color: black">
      <div class="card">
        <div class="card-body">
          <p class="judul">{{ donasi.judul }}</p>
          <p class="pemilik">{{ donasi.pemilik }}</p>
          <p class="terkumpul">Terkumpul: Rp. {{ donasi.dana_terkumpul }}</p>
          <div class="image" style="background-image: url({{ donasi.get_image_data }});"></div>
        </div>
      </div>
    </a>
    {% endfor %}
    {% else %}
    Donasi masih kosong...
    {% endif %}
  </div>
  <h2 class="mt-5">Donasi Ditolak</h2>
  <div>
    {% if donasi_ditolak|length != 0 %}
    {% for donasi in donasi_ditolak %}
    <a href="{% url 'donasi:admin-detail' donasi.id %}" style="color: black">
      <div class="card">
        <div class="card-body">
          <p class="judul">{{ donasi.judul }}</p>
          <p class="pemilik">{{ donasi.pemilik }}</p>
          <p class="terkumpul">Terkumpul: Rp. {{ donasi.dana_terkumpul }}</p>
          <div class="image" style="background-image: url({{ donasi.get_image_data }});"></div>
        </div>
      </div>
    </a>
    {% endfor %}
    {% else %}
    Donasi masih kosong...
    {% endif %}
  </div>
</div>
{% endblock %}

donasi/templates/donasi/bayar.html
{% extends 'adopskuy/base.html' %}
{% load static %}

{% block style %}
<link href="{% static 'donasi/donasi.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mt-5" >{{ donasi.judul }}</h1>
  <div class="card my-3">
    <div class="card-body text-center">
      <p>Transfer ke nomor rekening berikut: ({{ bank }})</p>
      <h2>1234 1234 1234 1234</h2>
      <p>Jumlah yang ditransfer</p>
      <h3>Rp. {{ nominal }}</h3>
    </div>
  </div>
  <form action="{% url 'donasi:kirim' donasi.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="nominal" value="{{ nominal }}">
    <button type="submit" class="btn btn-primary my-3" href="{% url 'donasi:home' %}" style="width: 100%">SELESAI TRANSFER</button>
  </form>
  <div class="card my-3">
    <div class="card-body">
      <h2>Cerita</h2>
      <p>{{ donasi.deskripsi }}</p>
    </div>
  </div>
  {% with donasi.pemilik as pemilik %}
  <div class="card my-3">
    <div class="card-body">
      <h3 class="card-title">Data Pemilik</h3>
      <table>
        <tr>
          <td>Nama</td>
          <td>: {{ pemilik.nama_lengkap }}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td>: {{ pemilik.email }}</td>
        </tr>
        <tr>
          <td>Alamat</td>
          <td>: {{ pemilik.alamat }}</td>
        </tr>
        <tr>
          <td>Nomor Telepon</td>
          <td>: {{ pemilik.phone_number }}</td>
        </tr>
      </table>
    </div>
  </div>
  {% endwith %}
</div>
{% endblock %}

{% block script %}
<script src="{% static 'donasi/donate.js' %}"></script>
{% endblock %}

donasi/templates/donasi/detail.html
{% extends 'adopskuy/base.html' %}
{% load static %}

{% block style %}
<link href="{% static 'donasi/donasi.css' %}" rel="stylesheet">
<style>
div.image {
  margin: 40px 0 20px;
  height: 300px;
  background-color: #294e28;
  background-image: url({{ donasi.get_image_data }});
  background-size: cover;
  background-position: center;
}
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="image"></div>
  <h1>{{ donasi.judul }}</h1>
  <div class="card my-3">
    <div class="card-body">
      <p>Target: {{ donasi.target }}</p>
      <p>Dana Terkumpul: {{ donasi.dana_terkumpul }}</p>
    </div>
  </div>
  <button class="btn btn-success" onclick="btnDonate()" style="width: 100%">KIRIM DONASI</button>
  <div class="card my-3">
    <div class="card-body">
      <h2 class="card-title">Cerita</h2>
      <p>{{ donasi.deskripsi }}</p>
    </div>
  </div>
  {% with donasi.pemilik as pemilik %}
  <div class="card my-3">
    <div class="card-body">
      <h3 class="card-title">Data Pemilik</h3>
      <table>
        <tr>
          <td>Nama</td>
          <td>: {{ pemilik.nama_lengkap }}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td>: {{ pemilik.email }}</td>
        </tr>
        <tr>
          <td>Alamat</td>
          <td>: {{ pemilik.alamat }}</td>
        </tr>
        <tr>
          <td>Nomor Telepon</td>
          <td>: {{ pemilik.phone_number }}</td>
        </tr>
      </table>
    </div>
  </div>
  {% endwith %}
  {% if request.user == donasi.pemilik %}
  <div class="card my-3">
    <div class="card-body">
      <h5 class="card-title">Pengaturan (untuk pemilik)</h5>
      <form action="{% url 'donasi:ubah-gambar' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        Ubah gambar:
        <input type="hidden" name="donasi_id" value="{{ donasi.id }}">
        <input type="file" name="gambar">
        <button type="submit">Submit</button>
      </form>
    </div>
  </div>
  {% endif %}
  <div class="grey-screen" onclick="closePopup()"></div>
  <div class="card card-centered">
    <form id="form-popup" method="POST" action="{% url 'donasi:bayar' %}">
      {% csrf_token %}
      <input type="hidden" name="donasi_id" value="{{ donasi.id }}">
      <div class="card-body choose-nominal">
        <h3>Nominal</h3>
        <label for="10000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="10000" name="nominal" value="10000">
              Rp 10.000
            </div>
          </div>
        </label>
        <label for="20000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="20000" name="nominal" value="20000">
              Rp 20.000
            </div>
          </div>
        </label>
        <label for="50000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="50000" name="nominal" value="50000">
              Rp 50.000
            </div>
          </div>
        </label>
        <label for="100000">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="100000" name="nominal" value="100000">
              Rp 100.000
            </div>
          </div>
        </label>
      </div>
      <div class="card-body choose-bayar" style="display: none">
        <h3>Bank Tujuan</h3>
        <label for="bni">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="bni" name="bayar" value="bni">
              BNI
            </div>
          </div>
        </label>
        <label for="bca">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="bca" name="bayar" value="bca">
              BCA
            </div>
          </div>
        </label>
        <label for="mandiri">
          <div class="card">
            <div class="card-body">
              <input type="radio" id="mandiri" name="bayar" value="mandiri">
              Mandiri
            </div>
          </div>
        </label>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'donasi/donate.js' %}"></script>
{% endblock %}

donasi/templates/donasi/list.html
{% extends 'adopskuy/base.html' %}
{% load static %}

{% block style %}
<style>
.card {
  margin: 10px 0;
  position: relative;
}
.judul {
  font-size: 18px;
  font-weight: bold;
}
.pemilik {
  font-size: 14px;
}
.card .image {
  position: absolute;
  right: 0;
  top: 0;
  height: 100%;
  width: 300px;
  background-color: #294E28;
  background-size: cover;
  background-position: center;
}
</style>
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mt-5">Donasi</h1>
  <div>
    {% if all_donasi|length != 0 %}
    {% for donasi in all_donasi %}
    <a href="{% url 'donasi:detail' donasi.id %}" style="color: black">
      <div class="card">
        <div class="card-body">
          <p class="judul">{{ donasi.judul }}</p>
          <p class="pemilik">{{ donasi.pemilik }}</p>
          <p class="terkumpul">Terkumpul: Rp. {{ donasi.dana_terkumpul }}</p>
          <div class="image" style="background-image: url({{ donasi.get_image_data }});"></div>
        </div>
      </div>
    </a>
    {% endfor %}
    {% else %}
    Donasi masih kosong...
    {% endif %}
  </div>
</div>
{% endblock %}