adopskuy/urls.py
from django.contrib import admin
from django.urls import path, include
from adopskuy.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('artikel/', include('artikel.urls')),
    path('donasi/', include('donasi.urls')),
    path('adopsi/', include('adopsi.urls')),
    path('akun/', include('akun.urls')),
]

akun/urls.py
from django.urls import path

from .views import register_view, login_view, logout_view

app_name = 'akun'

urlpatterns = [
    path('daftar/', register_view, name='daftar'),
    path('masuk/', login_view, name='login'),
    path('keluar/', logout_view, name='keluar')
]

akun/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, nama_lengkap=None, alamat=None, phone_number=None, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        user_obj = self.model(
            email = self.normalize_email(email),
            nama_lengkap=nama_lengkap,
            alamat=alamat,
            phone_number=phone_number,
        )
        user_obj.set_password(password) # change user password
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email,nama_lengkap=None, alamat = None, phone_number = None, password=None):
        user = self.create_user(
                email,
                nama_lengkap=nama_lengkap,
                alamat=alamat,
                phone_number=phone_number,
                password=password,
                is_staff=True
        )
        return user

    def create_superuser(self, email, nama_lengkap=None, alamat = None, phone_number = None , password=None):
        user = self.create_user(
                email,
                nama_lengkap=nama_lengkap,
                alamat=alamat,
                phone_number=phone_number,
                password=password,
                is_staff=True,
                is_admin=True
        )
        return user


class User(AbstractBaseUser):
    email               = models.EmailField(max_length=55, unique=True)
    nama_lengkap           = models.CharField(max_length=55)
    alamat                 = models.CharField(max_length=3000)
    phone_number        = models.CharField(max_length=15)
    active              = models.BooleanField(default=True) # can login
    staff               = models.BooleanField(default=False) # staff user non superuser
    admin               = models.BooleanField(default=False) # superuser
    timestamp           = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['nama_lengkap', 'alamat', 'phone_number'] #['nama_lengkap'] #python manage.py createsuperuser

    objects = UserManager()

    def __str__(self):
        return self.nama_lengkap

    def get_nama_lengkap(self):
        if self.nama_lengkap:
            return self.nama_lengkap
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

akun/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('nama_lengkap', 'email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('nama_lengkap', 'email', 'password', 'active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

akun/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib.auth import login, logout, authenticate 
from django.contrib import messages
from .models import User

def register_view(request):
    if(request.method == "POST"):
        nama_lengkap = request.POST['namaLengkap']
        alamat = request.POST['alamat']
        no_telp = request.POST['noTelp']
        email = request.POST['emailVar']
        password = request.POST['passwordVar']

        validation, check_msg = check_validity(email, password)
        if(validation == True):
            buat_akun(nama_lengkap, alamat, no_telp, email, password)
            check_msg = 'Akun berhasil dibuat! Selamat datang.'
            messages.success(request, check_msg)
            user = authenticate(request, username=email, password=password)
            login(request, user);   
            request.session.set_expiry(7200)
            return HttpResponseRedirect('/')
        else:
            messages.error(request, check_msg)
            return HttpResponseRedirect('/akun/daftar')
    else:
        context = {
            'page_title': 'Daftar | Adopskuy!'
        }

        return render(request, 'register.html', context)

def login_view(request):
    if(request.method == 'POST'):
        username = request.POST['emailForm']
        password = request.POST['passwordForm']
        user = authenticate(request, username=username, password=password)

        if(user is not None ):  
            login(request, user);   
            request.session.set_expiry(7200)
            return HttpResponseRedirect('/')
        else:
            messages.error(request, "Email/password tidak cocok! Silakan coba lagi.")
    context = {
        'page_title': 'Masuk | Adopskuy!'
    }

    return render(request, 'login.html', context)

def buat_akun(nama_lengkap, alamat, no_telp, email, password):
    User.objects.create_user(email, nama_lengkap, alamat, no_telp, password)
    return True

def check_validity(email, password):
    email_pswd_check = check_validity_helper(email, password)
    if(email_pswd_check == True):
        email_not_exist = check_email_not_exist(email)
        message = "Valid!" if email_not_exist else "Email sudah terdaftar sebelumnya! Silakan gunakan email lain."
        return email_not_exist, message
    message = "Email/password tidak valid!"
    return False, message;

def check_email_not_exist(email):
     return not User.objects.filter(email=email).exists()

def check_validity_helper(email, password):
    try:
        split_email = email.split("@")
        split_domain = split_email[1].split(".")
    except:
        return False

    len_check = len(password) >= 8
    upper_check = any(c.isupper() for c in password)
    lower_check = any(c.islower() for c in password)
    num_check = any(c.isnumeric() for c in password)

    return len_check and upper_check and lower_check and num_check

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/akun/masuk')

akun/templates/login.html
{% extends 'adopskuy/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'akun-style.css' %}">  
{% endblock style %}
{% block head %}
<title>Registrasi | Adopskuy!</title>
{% endblock %}

{% block content %}
  <div class="bg-green px-5 py-5 masuk-body">
    {% if messages %}
      <div class="span12">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}">
            {{ message }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
    <div class="masuk-content pt-5 px-5 pb-3">
        <div id="text-container-1">
            <h4 class="daftar-title" style="color: #262626!important;">Masuk ke Aplikasi</h4>
            <p style="color: #262626!important;">Silakan masuk untuk mulai mengakses layanan kami</p>
            <hr>
        </div>
        <div class="form-container mt-4">
            <form method="POST" action="{% url 'akun:login' %}">
                {% csrf_token %}
                <div class="form-group">
                  <label for="emailForm" style="color: #262626!important;">Email address</label>
                  <input type="email" class="form-control" id="emailForm" name="emailForm" 
                  placeholder="Enter email">
                </div>
                <div class="form-group">
                  <label for="passwordForm" style="color: #262626!important;">Password</label>
                  <input type="password" class="form-control" id="passwordForm" name="passwordForm" 
                  placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary px-5 py-2 mt-4" style="width: 100%!important;">Masuk</button>
              </form>
            </div>
            <div class="mt-4" style="display: flex; justify-content:center;align-items: center;">
              <p>Belum punya akun? <span><a href="/akun/daftar">Daftarkan dirimu di sini.</a></span></p>
          </div>
    </div>
</div>
{% endblock %}

akun/templates/register.html
{% extends 'adopskuy/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'akun-style.css' %}">  
{% endblock style %}
{% block head %}
<title>Registrasi | Adopskuy!</title>
{% endblock %}

{% block content %}
<div class="bg-green px-5 py-5">
    {% if messages %}
        <div class="span12">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="card-bg pt-5 px-5 pb-3">
        <div id="text-container-1">
            <h4 class="daftar-title">Registrasi Akun</h4>
            <p>Daftarkan dirimu untuk dapat mengakses layanan kami!</p>
            <hr>
        </div>
        <div class="form-container mt-4">
            <form method="POST" action="{% url 'akun:daftar' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="namaLengkap">Nama Lengkap</label>
                    <input type="text" class="form-control" id="namaLengkap" name="namaLengkap" 
                    placeholder="e.g. Cicak bin Kadal">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="text" class="form-control" id="alamat" name="alamat" 
                    placeholder="e.g. Pamulang, Jawa">
                </div>
                <div class="form-group">
                    <label for="noTelp">Nomor Telepon</label>
                    <input type="text" class="form-control" id="noTelp" name="noTelp" 
                    placeholder="e.g. 087777535244">
                </div>
                <div class="form-group">
                  <label for="emailVar">Email address</label>
                  <input type="email" class="form-control" id="emailVar" name="emailVar" 
                  aria-describedby="emailHelp" placeholder="e.g. someone@mail.com">
                  <small id="emailHelp" class="form-text text-muted">Email anda aman bersama kami. :)</small>
                </div>
                <div class="form-group">
                  <label for="passwordVar">Password</label>
                  <input type="password" class="form-control" id="passwordVar" name="passwordVar" 
                  placeholder="Password" aria-describedby="pswdHelp">
                  <small id="pswdHelp" class="form-text text-muted">Password harus mengandung Uppercase, Lowercase dan Numerik.</small>
                </div>
                <button type="submit" class="btn btn-primary px-5 py-2 mt-4">Buat Akun</button>
              </form>
        </div>
        <div class="mt-4">
            <p>Sudah punya akun? <span><a href="/akun/masuk">Masuk di sini.</a></span></p>
        </div>
    </div>
</div>
{% endblock %}