adopskuy/urls.py
from django.contrib import admin
from django.urls import path, include
from adopskuy.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('artikel/', include('artikel.urls')),
    path('donasi/', include('donasi.urls')),
    path('adopsi/', include('adopsi.urls')),
    path('akun/', include('akun.urls')),
]

akun/urls.py
from django.urls import path

from .views import register_view, login_view, logout_view

app_name = 'akun'

urlpatterns = [
    path('daftar/', register_view, name='daftar'),
    path('masuk/', login_view, name='login'),
    path('keluar/', logout_view, name='keluar')
]

artikel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from artikel.views import home, artikel, hapus_artikel

app_name = 'artikel'

urlpatterns = [
    path('', home, name='home'),
    path('view/<int:id_artikel>/', artikel, name='artikel'),
    path('delete/<int:id_artikel>/', hapus_artikel, name='hapus_artikel')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artikel/models.py
from akun.models import User
from django.db import models
from django.dispatch import receiver
import os

# Create your models here.

def get_image_path(instance, filename):
    return os.path.join('artikel', str(instance.penulis.id), filename)

class Artikel(models.Model):
    id_artikel = models.AutoField(primary_key=True)
    judul = models.CharField(max_length=256)
    isi = models.TextField()
    penulis = models.ForeignKey(User, 
        on_delete=models.CASCADE, 
        null=True, 
        blank=True
    )
    gambar = models.ImageField(
        upload_to=get_image_path,
        default = "static/artikel/artikel-jumbo.png"
    )
    tanggal_publikasi = models.DateTimeField(auto_now_add=True)
    terakhir_dimodifikasi = models.DateTimeField(auto_now=True)

    def get_id(self):
        return self.id_artikel
        

@receiver(models.signals.post_delete, sender=Artikel)
def auto_delete_gambar_on_delete(sender, instance, **kwargs):
    """
    Deletes gambar from filesystem
    when corresponding `Artikel` object is deleted.
    """
    if instance.gambar:
        if os.path.isfile(instance.gambar.path):
            os.remove(instance.gambar.path)

artikel/forms.py
from django import forms
from artikel.models import Artikel

class ArtikelForm(forms.ModelForm):
    class Meta:
        model = Artikel

        fields = [
            'judul', 
            'isi',
            'gambar'
        ]

        labels = {
            'judul':'Judul',
            'isi':'Isi Artikel',
            'gambar':'Gambar'
        }

        widgets = {
            'judul':forms.TextInput(
                attrs = {
                    'class':'form-control',
                    'placeholder':'Masukkan judul artikel'
                }
            ),
            'isi':forms.Textarea(
                attrs = {
                    'class':'form-control'
                }
            ),
            'gambar':forms.ClearableFileInput(
                attrs = {
                    'onchange':'sub(this)'
                }
            )
        }

artikel/views.py
from django.core import paginator
from django.core.paginator import Paginator
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from artikel.forms import ArtikelForm
from artikel.models import Artikel

# Create your views here.
def home(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = ArtikelForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                artikel = form.save(commit=False)
                artikel.penulis = request.user
                artikel.save()
                return JsonResponse({"success": True})
    else:
        form = ArtikelForm()
    
    artikel_list = get_artikel_order_by('-terakhir_dimodifikasi')
    paginator = Paginator(artikel_list, 5)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_title':'Artikel',
        'page_obj': page_obj,
        'artikel_form':form
    }

    return render(request, 'artikel/home.html', context)


def artikel(request, id_artikel):
    artikel_obj = get_artikel(id_artikel)
    random_artikel = get_artikel_order_by("?")[:5]

    if request.method == 'POST':
        if request.user.is_authenticated:
            form = ArtikelForm(request.POST or None, request.FILES or None, instance=artikel_obj)
            if form.is_valid():
                form.save()
                return JsonResponse({"success": True})
    else:
        form = ArtikelForm(instance=artikel_obj)

    context = {
        'page_title':'Mengerti Hewan Peliharaanmu',
        'artikel_obj':artikel_obj,
        'artikel_form':form,
        'random_artikel':random_artikel
    }

    return render(request, 'artikel/artikel.html', context)


def hapus_artikel(request, id_artikel):
    artikel_obj = get_artikel(id_artikel)
    artikel_obj.delete()
    return HttpResponseRedirect("/artikel/")


def get_all_artikel():
    return Artikel.objects.all()


def get_artikel_order_by(order_by):
    return Artikel.objects.order_by(order_by)


def get_artikel(id_artikel):
    return get_object_or_404(Artikel, id_artikel=id_artikel)

artikel/templates/artikel/artikel.html
{% extends "adopskuy/base.html" %}
{% load static %}
<body data-media-url="{% get_media_prefix %}">

{% block style %}
<link rel="stylesheet" href="{% static 'artikel/artikel-artikel.css' %}">
<link rel="stylesheet" href="{% static 'artikel/modal.css' %}">
<link rel="stylesheet" href="{% static 'artikel/tooltip.css' %}">
<link rel="stylesheet" href="{% static 'artikel/form.css' %}">
<link rel="stylesheet" href="{% static 'artikel/custom-button.css' %}">
<style>
    .jumbo {
        height:400px;
        width:100%;
        {% if 'static' in artikel_obj.gambar.url %}
        background: #294E28;
        color: white;
        {% else %}
        background: url("../..{{ artikel_obj.gambar.url }}");
        {% endif %}
        background-position: center;
        background-repeat: no-repeat;
        background-size:cover;
    }
    
    a {
        text-decoration: none;
        color: black;
    }

    a:hover {

        color: black;
    }
</style>
{% endblock style %}

{% block content %}
<div>
    <div class="d-flex justify-content-center jumbo" style="flex-direction:column;">
        <div class="container">
            <h2><b>{{ artikel_obj.judul }}</b></h2>
        </div>
        <div class="container">
            oleh {{ artikel_obj.penulis.nama_lengkap }} | {{ artikel_obj.tanggal_publikasi }}
        </div>
    </div>
</div>

<div class="container main-body">
    <div class="d-flex justify-content-center">
        <div class="left-tab d-flex flex-column text-center">
            {% if artikel_obj.penulis.id == request.user.id %}
                <div class="m-1">
                    <span>Kelola Artikel ini</span>
                </div>
                <div class="m-1 d-flex justify-content-center">
                    <div class="m-1">
                        <button type="button" class="btn custom-button" id="myBtn">Edit</button>
                    </div>
                    <div class="m-1">
                        <button type="button" class="btn custom-button" onclick="deleteArticle()">Hapus</button>
                    </div>
                </div>
            {% endif %}
            <div class="m-1">
                <hr>           
            </div>
            <div class="m-1">
                <span>Bagikan Artikel</span>
            </div>
            <div class="m-1 tooltip text-center">
                <button onclick="myFunc()" onmoouseout="outFunc()" type="button" class="btn custom-button">
                    <span class="tooltiptext" id="myTooltip">Copy ke clipboard!</span>
                    Copy link!
                </button>
            </div>
            <div><hr></div>
            <div class="m-1">
                <span>Artikel Lainnya</span>            
            </div>
            {% for artikel in random_artikel %}
                <div class="m-1">
                    <a href="{% url 'artikel:artikel' artikel.id_artikel %}">
                        <span><b>{{ artikel.judul }}</b></span>
                    </a>
                    <span>oleh {{ artikel.penulis.nama_lengkap }}</span>
                </div>
                <div class="m-1"><hr></div>
            {% endfor %}
        </div>
        <div class="isi-artikel px-4" style="text-align:justify;">
            <div>
                <p>
                {{ artikel_obj.isi | linebreaks }}
                </p>
            </div>
        </div>
    </div>

    {% if request.user.is_admin %}
        <div id="myModal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <span id="header-text">Edit Artikel</span>
                    <span class="close">&times;</span>
                </div>
                <div class="modal-body">
                    <form id="data" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in artikel_form %}
                            {% if field.html_name != 'gambar' %}
                                <div class="form-group">
                                    <b>{{ field.label_tag }}</b> 
                                    {{ field }}
                                </div>
                            {% else %}
                                <div class="form-group">
                                    <div id="yourBtn" onclick="getFile()">Upload Gambar disini!</div>
                                    <div style='height: 0px;width: 0px; overflow:hidden;'>
                                        {{ field }}
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <button type="submit" class="btn custom-button float-right" style="margin-bottom:50px;">Simpan</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <small>Copyright &copy; Adopskuy 2020</small>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'artikel/modal.js' %}"></script>
<script src="{% static 'artikel/tooltip.js' %}"></script>
<script>
    function deleteArticle() {
        Swal.fire({
            title: 'Apakah anda yakin?',
            text: "Artikel ini tidak akan dapat di-recover!",
            icon: 'warning',
            showCancelButton: true,
            cancelButtonText: "Tidak!",
            confirmButtonColor: '#294E28',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, hapus!',
            showLoaderOnConfirm: true,
            preConfirm: () => {
                return fetch(`{% url 'artikel:hapus_artikel' artikel_obj.id_artikel %}`)
                    .then(response => {
                        if (!response.ok) {
                            throw new Error(response.statusText)
                        }
                    })
                    .catch(error => {
                        Swal.showValidationMessage(
                            `Gagal terhapus!`
                        )
                    })
            },
            allowOutsideClick: () => !Swal.isLoading()
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire({
                    icon: 'success',
                    title: 'Terhapus!',
                    allowOutsideClick: false,
                    html: 'Artikel berhasil terhapus.<br>Kembali ke halaman Artikel dalam <b></b> milisekon.',
                    showConfirmButton: false,
                    timer: 3000,
                    timerProgressBar: true,
                    didOpen: () => {
                        Swal.showLoading()
                        timerInterval = setInterval(() => {
                        const content = Swal.getContent()
                        if (content) {
                            const b = content.querySelector('b')
                            if (b) {
                            b.textContent = Swal.getTimerLeft()
                            }
                        }
                        }, 100)
                    },
                    willClose: () => {
                        clearInterval(timerInterval)
                    }, 
                    didClose: () => {
                        window.location.replace("/artikel/");
                    }
                });
            }
        })
    }
</script>
<script>
$("form#data").submit(function(e) {
    e.preventDefault();
    var formData = new FormData(this);
    
    $.ajax({
        url: window.location.pathname,
        type: "POST",
        data: formData,
        success: function (data) {
            Swal.fire({
                icon: 'success',
                title: 'Tersimpan!',
                allowOutsideClick: false,
                html: 'Artikel berhasil Tersimpan.<br>Halaman akan ter-refresh dalam <b></b> milisekon.',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: () => {
                    Swal.showLoading()
                    timerInterval = setInterval(() => {
                    const content = Swal.getContent()
                    if (content) {
                        const b = content.querySelector('b')
                        if (b) {
                        b.textContent = Swal.getTimerLeft()
                        }
                    }
                    }, 100)
                },
                willClose: () => {
                    clearInterval(timerInterval)
                }, 
                didClose: () => {
                    window.location.replace("/artikel/view/{{ artikel_obj.id_artikel }}");
                }
            });                
        },
        error: function (e) {
            console.log(e);
        },
        cache: false,
        contentType: false,
        processData: false
    });
});
</script>
{% endblock script %}

artikel/templates/artikel/home.html
{% extends "adopskuy/base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'artikel/artikel-home.css' %}">
<link rel="stylesheet" href="{% static 'artikel/custom-button.css' %}">
<link rel="stylesheet" href="{% static 'artikel/modal.css' %}">
<link rel="stylesheet" href="{% static 'artikel/form.css' %}">
{% endblock style %}

{% block content %}
<div class="jumbotron" style="background-color: #294E28; border-radius:0; height:300px">
    <div class="container">
        <h1 style="text-align: center; color: white; line-height: 150px;"><b>Artikel</b></h1>
    </div>
</div>

{% if page_obj %}
    {% if request.user.is_admin %}
    <div class="d-flex justify-content-center">
        <div>
            <button type="button" class="btn custom-button" id="myBtn">Tambah Artikel</button>
        </div>
    </div>
    {% endif %}
    <div class="container my-3">
        {% for artikel in page_obj %}
        <div class="d-flex flex-column">
            <div class="my-3 py-3">
                <span>{{ artikel.penulis.nama_lengkap }} menulis</span>
                <h3><a href="{% url 'artikel:artikel' artikel.id_artikel %}" style="color:inherit;"><b>{{artikel.judul}}</b></a></h3>
                <p style="text-align: justify; margin-bottom: 0;">
                    <span class="artikel-date"><i>{{ artikel.tanggal_publikasi }} - </i></span>
                    {{ artikel.isi | truncatewords:50 }}
                </p>
                <a href="{% url 'artikel:artikel' artikel.id_artikel %}"><u>Baca...</u></a>
            </div>
        </div>
        {% endfor %}
    </div>


    <div class="pagination justify-content-center" style="margin-bottom:50px;">
        <span class="step-links d-flex align-items-center">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="no-dec">
                    <div class="d-flex justify-content-center align-items-center page-num">
                        <<
                    </div>
                </a>
                
                <a href="?page={{ page_obj.previous_page_number }}" class="no-dec">
                    <div class="d-flex justify-content-center align-items-center page-num">
                        <
                    </div>
                </a>
            {% endif %}

            <div>
                <span class="current">
                    Halaman {{ page_obj.number }} dari {{ page_obj.paginator.num_pages }}.
                </span>
            </div>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="no-dec">
                    <div class="d-flex justify-content-center align-items-center page-num">
                        >
                    </div>
                </a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="no-dec">
                    <div class="d-flex justify-content-center align-items-center page-num">
                        >>
                    </div>
                </a>
            {% endif %}
        </span>
    </div>
{% else %}
    {% if request.user.is_admin %}
    <div class="text-center m-3">
        <span style="font-size:20pt;">Belom ada yang berani nulis Artikel nih. Yuk tulis artikelmu!</span>
    </div>
    <div class="d-flex justify-content-center">
        <div>
            <button type="button" class="btn custom-button" id="myBtn">Tambah Artikel</button>
        </div>
    </div>
    {% else %}
    <div class="text-center m-3">
        <span style="font-size:20pt;">Mohon maaf, tidak terdapat Artikel yang tersedia.</span>
    </div>
    {% endif %}
{% endif %}

{% if request.user.is_admin %}
    <div id="myModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <span id="header-text">Buat Artikel</span>
                <span class="close">&times;</span>
            </div>
            <div class="modal-body">
                <form id="data" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in artikel_form %}
                        {% if field.html_name != 'gambar' %}
                            <div class="form-group">
                                <b>{{ field.label_tag }}</b> 
                                {{ field }}
                            </div>
                        {% else %}
                            <div class="form-group">
                                <div id="yourBtn" onclick="getFile()">Upload Gambar disini!</div>
                                <div style='height: 0px;width: 0px; overflow:hidden;'>
                                    {{ field }}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn custom-button float-right" style="margin-bottom:50px;">Simpan</button>
                </form>
            </div>
            <div class="modal-footer">
                <small>Copyright &copy; Adopskuy 2020</small>
            </div>
        </div>
    </div>
{% endif %}
{% endblock content %}

{% block script %}
<script src="{% static 'artikel/modal.js' %} "></script>
<script>
$("form#data").submit(function(e) {
    e.preventDefault();
    var formData = new FormData(this);
    
    $.ajax({
        url: window.location.pathname,
        type: "POST",
        data: formData,
        success: function (data) {
            Swal.fire({
                icon: 'success',
                title: 'Tersimpan!',
                allowOutsideClick: false,
                html: 'Artikel berhasil Tersimpan.<br>Kembali ke halaman Artikel dalam <b></b> milisekon.',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: () => {
                    Swal.showLoading()
                    timerInterval = setInterval(() => {
                    const content = Swal.getContent()
                    if (content) {
                        const b = content.querySelector('b')
                        if (b) {
                        b.textContent = Swal.getTimerLeft()
                        }
                    }
                    }, 100)
                },
                willClose: () => {
                    clearInterval(timerInterval)
                }, 
                didClose: () => {
                    window.location.replace("/artikel/");
                }
            });                
        },
        error: function (e) {
            console.log(e);
        },
        cache: false,
        contentType: false,
        processData: false
    });
});
</script>
{% endblock script %}