adopsi/urls.py
from django.urls import path, include, re_path
from adopsi.views import *
from django.conf.urls.static import static
from django.conf import settings


app_name = 'adopsi'

urlpatterns = [
    path(route="",view=main_view, name="adopsi"),
    path('view/<int:id_adopsi>/', adopsi, name='view'),
    path('delete/<int:id_adopsi>/', hapus_adopsi, name='hapus_adopsi')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adopskuy/urls.py
from django.contrib import admin
from django.urls import path, include
from adopskuy.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('artikel/', include('artikel.urls')),
    path('donasi/', include('donasi.urls')),
    path('adopsi/', include('adopsi.urls')),
    path('akun/', include('akun.urls')),
]

akun/urls.py
from django.urls import path

from .views import register_view, login_view, logout_view

app_name = 'akun'

urlpatterns = [
    path('daftar/', register_view, name='daftar'),
    path('masuk/', login_view, name='login'),
    path('keluar/', logout_view, name='keluar')
]

adopsi/models.py
from django.db import models
from akun.models import User
from django.dispatch import receiver
import os

# Create your models here.

def get_image_path(instance, filename):
    return os.path.join('adopsi', str(instance.pemilik.id), filename)

class Adopsi(models.Model):
    id_adopsi = models.AutoField(primary_key=True)
    judul = models.CharField(max_length=100)
    deskripsi = models.TextField()
    pemilik = models.ForeignKey(User,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    gambar = models.ImageField(
        upload_to=get_image_path,
        default = "static/adopsi/placeholder.png"
    )

    def get_id(self):
        return self.id_artikel

@receiver(models.signals.post_delete, sender=Adopsi)
def auto_delete_gambar_on_delete(sender, instance, **kwargs):
    """
    Deletes gambar from filesystem
    when corresponding `Adopsi` object is deleted.
    """
    if instance.gambar:
        if os.path.isfile(instance.gambar.path):
            os.remove(instance.gambar.path)

adopsi/forms.py
from django import forms
from adopsi.models import Adopsi

class AdopsiForm(forms.ModelForm):
    class Meta:
        model = Adopsi

        fields = [
            'judul',
            'deskripsi',
            'gambar'
        ]

        labels = {
            'judul':'Judul',
            'deskripsi':'Deskripsi Hewan',
            'gambar':'Gambar'
        }

        widgets = {
            'judul':forms.TextInput(
                attrs = {
                    'class':'form-control',
                    'placeholder':'Masukkan judul post Adopsi'
                }
            ),
            'deskripsi':forms.Textarea(
                attrs = {
                    'class':'form-control'
                }
            ),
            'gambar':forms.ClearableFileInput(
                attrs = {
                    'onchange':'sub(this)'
                }
            )
        }

adopsi/views.py
from django.core import paginator
from django.core.paginator import Paginator
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from adopsi.forms import AdopsiForm
from adopsi.models import Adopsi


# Create your views here.
def main_view(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = AdopsiForm(request.POST or None, request.FILES or None )
            if form.is_valid():
                adopsi = form.save(commit=False)
                adopsi.pemilik = request.user
                adopsi.save()
                return JsonResponse({"success":True})
    else:
        form = AdopsiForm()
    
    adopsi_list = get_all_adopsi()
    paginator = Paginator(adopsi_list, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_title': 'Adopsi',
        'page_obj': page_obj,
        'adopsi_form': form,
        'adopsi_list' : adopsi_list
    }

    return render(request, 'main.html', context)


def adopsi(request, id_adopsi):
    adopsi_obj = get_adopsi(id_adopsi)

    if request.method == "POST":
        if request.user.is_authenticated:
            form = AdopsiForm(request.POST or None, request.FILES or None, instance=adopsi_obj)
            if form.is_valid():
                form.save()
                return JsonResponse({"success":True})
    else:
        form = AdopsiForm(instance=adopsi_obj)
    
    context = {
        "page_title": "Adopsi",
        "adopsi_obj": adopsi_obj,
        "adopsi_form": form
    }

    return render(request, 'full_desc.html', context)

def hapus_adopsi(request, id_adopsi):
    adopsi_obj = get_adopsi(id_adopsi)
    adopsi_obj.delete()
    return HttpResponseRedirect("/adopsi/")

def get_all_adopsi():
    return Adopsi.objects.all()

def get_adopsi(id_adopsi):
    return get_object_or_404(Adopsi, id_adopsi=id_adopsi)

def get_adopsi_filter(name_filter):
    return Adopsi.objects.filter(judul__icontains=name_filter)

adopsi/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Shojumaru&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'akun-style.css' %}">
  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-green px-5">
        <a class="navbar-brand logo-style" href="/">Adopskuy!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-1">
              <a class="nav-link" href="/">Beranda</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="/adopsi">Adopsi</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="/donasi">Donasi</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="/artikel">Artikel</a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="/masuk">Masuk</a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="/daftar">Daftar</a>
            </li>
          </ul>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"
  ></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

adopsi/templates/form.html
{% extends "base.html" %}

{% block head %}

{% endblock%}

{% block content %}
<div class="jumbotron" style="background-color: #294E28; border-radius:0; height:300px">
    <div class="container">
        <h1 style="text-align: center; color: white; line-height: 150px;"><b>Edit/Tambah Adopsi</b></h1>
    </div>
</div>

<div class="container" style="padding-top:50px;">
    <form action="">
        <div class="form-group">
            <label for="exampleInputEmail1">Judul</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Fulan" value="Mengerti Hewan Peliharaanmu">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Deskripsi</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="validatedCustomFile">Gambar</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="validatedCustomFile" required>
                <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
            </div>
        </div>
        <button type="submit" class="btn custom-button">Submit</button>
    </form>
</div>

{% endblock %}

adopsi/templates/full_desc.html
{% extends "adopskuy/base.html" %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'artikel/artikel-artikel.css' %}">
<link rel="stylesheet" href="{% static 'artikel/modal.css' %}">
<link rel="stylesheet" href="{% static 'artikel/tooltip.css' %}">
<link rel="stylesheet" href="{% static 'artikel/form.css' %}">
<link rel="stylesheet" href="{% static 'artikel/custom-button.css' %}">
{% endblock style%}

{% block content %}
<div class="jumbotron" style="background-color: #294E28; border-radius:0; height:100px">
    <div class="container">
        <h1 style="text-align: center; color: white; line-height: 50px;"><b>Adopsi</b></h1>
    </div>
</div>

<div>
    <div class="d-flex justify-content-center jumbo" style="flex-direction:column;">
        <div class="container">
            <h2><b>{{ adopsi_obj.judul }}</b></h2>
        </div>
    </div>
</div>

<div class="container">
    <div class="d-flex p-2 bd-highlight">
        <div class="card" style="width: 20rem; background-color: gray;">
            
            <div class="card-body">
            {% if 'static' in adopsi_obj.gambar.url %}
            <img src="{% static 'adopsi/placeholder.png' %}" style="max-width: 100%;">
            {% else %}
            <img src=" ../..{{adopsi_obj.gambar.url}}" style="max-width: 100%;">
            {% endif %}   
            
            </div>
        </div>
        <div class="container">
            {{adopsi_obj.deskripsi}}
        </div>
    </div>
    <div class="container-sm">
        Nama pemilik: {{adopsi_obj.pemilik.nama_lengkap}}
        <br>
        Untuk informasi lebih lanjut silahkan hubungi pemilik: {{adopsi_obj.pemilik.phone_number}}
    </div>
    <br>
    {% if adopsi_obj.pemilik.id == request.user.id %}
        <div class="m-1 d-flex justify-content-center">
            <span>Kelola Artikel ini</span>
        </div>
        <div class="m-1 d-flex justify-content-center">
            <div class="m-1">
                <button type="button" class="btn custom-button" id="myBtn">Edit</button>
            </div>
            <div class="m-1">
                <button type="button" class="btn custom-button" onclick="deleteArticle()">Hapus</button>
            </div>
        </div>
    {% endif %}
    {% if request.user.is_admin %}
    <div class="m-1 d-flex justify-content-center">
        <div class="m-1">
            <button type="button" class="btn custom-button" onclick="deleteArticle()">Hapus</button>
        </div>
    </div>
    {% endif %}
    {% if adopsi_obj.pemilik.id == request.user.id %}
    <div id="myModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <span id="header-text">Edit Adopsi</span>
                <span class="close">&times;</span>
            </div>
            <div class="modal-body">
                <form id="data" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in adopsi_form %}
                        {% if field.html_name != 'gambar' %}
                            <div class="form-group">
                                <b>{{ field.label_tag }}</b> 
                                {{ field }}
                            </div>
                        {% else %}
                            <div class="form-group">
                                <div id="yourBtn" onclick="getFile()">Upload Gambar disini!</div>
                                <div style='height: 0px;width: 0px; overflow:hidden;'>
                                    {{ field }}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn custom-button float-right" style="margin-bottom:50px;">Simpan</button>
                </form>
            </div>
            <div class="modal-footer">
                <small>Copyright &copy; Adopskuy 2020</small>
            </div>
        </div>
    </div>
{% endif %}
</div>

{% endblock content %}

{% block script %}
<script src="{% static 'artikel/modal.js' %}"></script>
<script src="{% static 'artikel/tooltip.js' %}"></script>
<script>
    function deleteArticle() {
        Swal.fire({
            title: 'Apakah anda yakin?',
            text: "Postingan adopsi ini tidak akan dapat di-recover!",
            icon: 'warning',
            showCancelButton: true,
            cancelButtonText: "Tidak!",
            confirmButtonColor: '#294E28',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, hapus!',
            showLoaderOnConfirm: true,
            preConfirm: () => {
                return fetch(`{% url 'adopsi:hapus_adopsi' adopsi_obj.id_adopsi %}`)
                    .then(response => {
                        if (!response.ok) {
                            throw new Error(response.statusText)
                        }
                    })
                    .catch(error => {
                        Swal.showValidationMessage(
                            `Gagal terhapus!`
                        )
                    })
            },
            allowOutsideClick: () => !Swal.isLoading()
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire({
                    icon: 'success',
                    title: 'Terhapus!',
                    allowOutsideClick: false,
                    html: 'Postingan adopsi berhasil terhapus.<br>Kembali ke halaman Artikel dalam <b></b> milisekon.',
                    showConfirmButton: false,
                    timer: 3000,
                    timerProgressBar: true,
                    didOpen: () => {
                        Swal.showLoading()
                        timerInterval = setInterval(() => {
                        const content = Swal.getContent()
                        if (content) {
                            const b = content.querySelector('b')
                            if (b) {
                            b.textContent = Swal.getTimerLeft()
                            }
                        }
                        }, 100)
                    },
                    willClose: () => {
                        clearInterval(timerInterval)
                    }, 
                    didClose: () => {
                        window.location.replace("/adopsi/");
                    }
                });
            }
        })
    }
</script>
<script>
$("form#data").submit(function(e) {
    e.preventDefault();
    var formData = new FormData(this);
    
    $.ajax({
        url: window.location.pathname,
        type: "POST",
        data: formData,
        success: function (data) {
            Swal.fire({
                icon: 'success',
                title: 'Tersimpan!',
                allowOutsideClick: false,
                html: 'Postingan adopsi berhasil Tersimpan.<br>Halaman akan ter-refresh dalam <b></b> milisekon.',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: () => {
                    Swal.showLoading()
                    timerInterval = setInterval(() => {
                    const content = Swal.getContent()
                    if (content) {
                        const b = content.querySelector('b')
                        if (b) {
                        b.textContent = Swal.getTimerLeft()
                        }
                    }
                    }, 100)
                },
                willClose: () => {
                    clearInterval(timerInterval)
                }, 
                didClose: () => {
                    window.location.replace("/adopsi/view/{{ adopsi_obj.id_adopsi }}");
                }
            });                
        },
        error: function (e) {
            console.log(e);
        },
        cache: false,
        contentType: false,
        processData: false
    });
});
</script>
{% endblock script %}

adopsi/templates/main.html
{% extends "adopskuy/base.html" %}
{% load static %}
{% block head %}
<title> Adopsi | Main</title>
{% endblock%}

{% block style %}
<link rel="stylesheet" href="{% static 'artikel/artikel-home.css' %}">
<link rel="stylesheet" href="{% static 'artikel/custom-button.css' %}">
<link rel="stylesheet" href="{% static 'artikel/modal.css' %}">
<link rel="stylesheet" href="{% static 'artikel/form.css' %}">
{% endblock style %}

{% block content %}
<div class="jumbotron" style="background-color: #294E28; border-radius:0; height:300px">
  <div class="container">
      <h1 style="text-align: center; color: white; line-height: 150px;"><b>Adopsi</b></h1>
  </div>
</div>
{% if page_obj%}
  <div class="container-fulid" >
    {% if request.user.is_authenticated %}
    <div class="d-flex justify-content-center">
      <div>
          <button type="button" class="btn custom-button" id="myBtn">Tambah Adopsi</button>
      </div>
    </div>
    <br>
    <div class="d-flex justify-content-center">
        <div>
          <button type="button" class="btn custom-button" id="myPost" value="{{request.user.nama_lengkap}}">Postingan saya</button>
      </div>
      </div>
    <br>
    {% endif %}
    <div class="d-flex justify-content-center">
       <div>
        <input class="form-control" id="myInput" type="text" style="border-color: green;" placeholder="Search" aria-label="Search">
      </div>
    </div>
    
      <br>
    <div class="container justify-content-center" style="height: 100%;">
        <ul class="container" id="myList" style="list-style-type: none; padding: 0;  margin: 0;">
      {% for adopsi in adopsi_list %}
      <li style="margin-left: 2%; float:left; margin-top: 2%; width: 20rem; height: 25rem;" >
      <div class="card" style="width: 18rem; min-height: 23rem; border-width: 2px;">
            {% if 'static' in adopsi.gambar.url %}
            <img src="{% static 'adopsi/placeholder.png' %}" style="max-width: 100%;">
            {% else %}
            <img src= "../adopsi{{adopsi.gambar.url}}" style="max-width: 100%;">
            {% endif %}  
        <div class="card-body" style="height:7rem;">
          <h5 class="card-title">{{adopsi.judul}}</h5>
        <p class="card-text">Pemilik: {{adopsi.pemilik.nama_lengkap}}</p> 
        <a href="view/{{adopsi.id_adopsi}}/"  class="btn btn-primary">Read More</a>    
         </div>
        
      </div>
     </li>
     
      {% endfor %}
    </ul>
    </div>
  </div>

 

{% else %}
  {% if request.user.is_authenticated %}
    <div class="text-center m-3">
      <span style="font-size:20pt;">Belom ada yang membuat postingan adopsi</span>
  </div>
  <div class="d-flex justify-content-center">
      <div>
          <button type="button" class="btn custom-button" id="myBtn">Tambah Adopsi</button>
      </div>
      <br>
      
</div>
  {% else %}
  <div class="text-center m-3">
    <span style="font-size:20pt;">Mohon maaf, tidak terdapat postingan adopsi yang tersedia.</span>
</div>
  {% endif %}
{% endif %}

{% if request.user.is_authenticated %}
<div id="myModal" class="modal">
  <div class="modal-content">
      <div class="modal-header">
          <span id="header-text">Buat Adopsi</span>
          <span class="close">&times;</span>
      </div>
      <div class="modal-body">
          <form id="data" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in adopsi_form %}
                  {% if field.html_name != 'gambar' %}
                      <div class="form-group">
                          <b>{{ field.label_tag }}</b> 
                          {{ field }}
                      </div>
                  {% else %}
                      <div class="form-group">
                          <div id="yourBtn" onclick="getFile()">Upload Gambar disini!</div>
                          <div style='height: 0px;width: 0px; overflow:hidden;'>
                              {{ field }}
                          </div>
                      </div>
                  {% endif %}
              {% endfor %}
              <button type="submit" class="btn custom-button float-right" style="margin-bottom:50px;">Simpan</button>
          </form>
      </div>
      <div class="modal-footer">
          <small>Copyright &copy; Adopskuy 2020</small>
      </div>
  </div>
</div>
{% endif %}

{% endblock content %}

{% block script %}
<script src="{% static 'adopsi/modal.js' %} "></script>
<script>
  $("form#data").submit(function(e) {
      e.preventDefault();
      var formData = new FormData(this);
      
      $.ajax({
          url: window.location.pathname,
          type: "POST",
          data: formData,
          success: function (data) {
              Swal.fire({
                  icon: 'success',
                  title: 'Tersimpan!',
                  allowOutsideClick: false,
                  html: 'Adopsi berhasil Tersimpan.<br>Kembali ke halaman Artikel dalam <b></b> milisekon.',
                  showConfirmButton: false,
                  timer: 3000,
                  timerProgressBar: true,
                  didOpen: () => {
                      Swal.showLoading()
                      timerInterval = setInterval(() => {
                      const content = Swal.getContent()
                      if (content) {
                          const b = content.querySelector('b')
                          if (b) {
                          b.textContent = Swal.getTimerLeft()
                          }
                      }
                      }, 100)
                  },
                  willClose: () => {
                      clearInterval(timerInterval)
                  }, 
                  didClose: () => {
                      window.location.replace("/adopsi/");
                  }
              });                
          },
          error: function (e) {
              console.log(e);
          },
          cache: false,
          contentType: false,
          processData: false
      });
  });

  $(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myList li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    
    $("#myPost").on("click", function(event) {
        var value = $(this).val().toLowerCase();
        console.log(value)
        $("#myList li").filter(function() {
            console.log($(this).children("div.card").children("div.card-body").children("p.card-text").text())
            $(this).toggle($(this).children("div.card").children("div.card-body").children("p.card-text").text().toLowerCase().indexOf(value) > -1)
            });
        });
    
    });


  </script>
{% endblock script %}

adopsi/templates/manage.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<title> Adopsi | Manage</title>
{% endblock%}

{% block content %}
<div class="jumbotron" style="background-color: #294E28; border-radius:0; height:300px">
    <div class="container">
        <h1 style="text-align: center; color: white; line-height: 150px;"><b>Manage Adopsi</b></h1>
    </div>
</div>
  <div class="container-fulid" style="flex: auto">
    <div class="card" style="width: 18rem;">
        <img src="{% static 'adopsi/placeholder.png' %} " class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Nama Hewan</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="full_desc" class="btn btn-primary">Read More</a>
          <a href="tambah" class="btn btn-primary">Edit</a>
          <a href="#" class="btn btn-primary">Hapus</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <img src="{% static 'adopsi/placeholder.png' %} " class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Nama Hewan</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="full_desc" class="btn btn-primary">Read More</a>
          <a href="tambah" class="btn btn-primary">Edit</a>
          <a href="#" class="btn btn-primary">Hapus</a>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <img src="{% static 'adopsi/placeholder.png' %}  " class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Nama Hewan</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="full_desc" class="btn btn-primary">Read More</a>
          <a href="tambah" class="btn btn-primary">Edit</a>
          <a href="#" class="btn btn-primary">Hapus</a>
        </div>
      </div>

      <a href="tambah" class="btn btn-primary">Tambah Adopsi</a>


  </div>
{% endblock %}